## Scraping Multiples Pages ShipInfo to get IMO and MMSI numbers.

_*Please, run each cell one by one. If you have any doubts, you may reach me out on <b>juan.fernandez.sea@gmail.com<b>*_

_*<b>Edit April-2-2024<b>*_

In [13]:
#importing the libraries needed for Web Scraping
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from time import sleep
from random import randint


#Declaring the list of empty variables, So that we can append the data overall

ship_name = []
IMO = []


#creating an array of values and passing it in the url for dynamic webpages
#Here we choose a vector from page 794 to 796 in "A" section to catch on purpose "Aurora Spirit" on our future list-DataFrame
pages = np.arange(794,796,1)

#the whole core of the script
for page in pages:
    page = requests.get("https://shipinfo.net/vessels_list.php?letter=A&page=" +str(page))
    soup = BeautifulSoup(page.text, 'html.parser')
    ship_data1 = soup.findAll('div', attrs = {'class': 'item'})
    ship_data = soup.findAll('div', attrs = {'class': 'description'})

    sleep(randint(2,8))
    for stored in ship_data:
        imo_d = stored.text
        IMO.append(imo_d)

    for store in ship_data1:
        name = store.a.text
        ship_name.append(name)
        
       
#creating a dataframe 
ship_list = pd.DataFrame({ "Ship Name": ship_name})

IMO_list = pd.DataFrame({"Ship Details" : IMO})

#Force Pandas Library to see all the elements of the Data frame
pd.set_option('display.max_rows', None)  # Mostrar todas las filas
pd.set_option('display.max_columns', None)  # Mostrar todas las columnas

In [16]:
#Visualize Ship Details Data Frame with 80 Elements that corresponds to the list provided by ShipInfo
IMO_list

                                         Ship Details
0    type: Offshore Supply Ship,  IMO: 9648025; MM...
1    type: Offshore Supply Ship,  IMO: 9648025; MM...
2    type: Research Vessel,  IMO: 8717283; MMSI: 2...
3                             IMO: 0; MMSI: 232023677
4    type: Passenger Ship,  IMO: 9196723; MMSI: 25...
5    type: Passenger/Landing Craft,  IMO: 7108100;...
6    type: Safety Vessel,  IMO: 9604885; MMSI: 372...
7    type: Offshore Supply Ship,  IMO: 9748344; MM...
8           type: Tug,  IMO: 8794140; MMSI: 525200151
9                             IMO: 0; MMSI: 219026609
10                            IMO: 0; MMSI: 258998740
11                            IMO: 0; MMSI: 316040487
12                            IMO: 0; MMSI: 316040366
13   type: General Cargo Ship,  IMO: 7600706; MMSI: 0
14                            IMO: 0; MMSI: 230157390
15                            IMO: 0; MMSI: 235007918
16                            IMO: 0; MMSI: 257695600
17   type: Wood Chips Carrier,  IMO: 9325087; MMSI...
18                            IMO: 0; MMSI: 224183630
19                            IMO: 0; MMSI: 235074996
20       type: Fishing Vessel,  IMO: 7804443; MMSI: 0
21                            IMO: 0; MMSI: 247034790
22                            IMO: 0; MMSI: 235006731
23   type: Offshore Supply Ship,  IMO: 9638123; MM...
24   type: Oil Products Tanker,  IMO: 9178018; MMS...
25   type: Oil Products Tanker,  IMO: 9178018; MMS...
26                            IMO: 0; MMSI: 258087150
27                            IMO: 0; MMSI: 258122330
28                            IMO: 0; MMSI: 257945800
29   type: Offshore Supply Ship,  IMO: 9665126; MM...
30    type: Pleasure craft ,  IMO: 0; MMSI: 211883350
31           type: VL,  IMO: 9837169; MMSI: 257086830
32                            IMO: 0; MMSI: 258268720
33      type: Research Vessel,  IMO: 7108112; MMSI: 0
34                            IMO: 0; MMSI: 310559020
35                            IMO: 0; MMSI: 310556030
36          type: LRS,  IMO: 9589774; MMSI: 775992150
37                            IMO: 0; MMSI: 257763310
38   type: Utility Vessel,  IMO: 9653214; MMSI: 23...
39                            IMO: 0; MMSI: 263933990
40   type: Passenger Ro Ro Cargo Ship\n,  IMO: 900...
41   type: Bulk Carrier\n,  IMO: 9270919; MMSI: 35...
42   type: Bulk Carrier\n,  IMO: 9214862; MMSI: 52...
43   type: Oil Products Tanker\n,  IMO: 9346445; M...
44   type: Bulk Carrier\n,  IMO: 9478810; MMSI: 21...
45                            IMO: 0; MMSI: 244025862
46                            IMO: 0; MMSI: 235075428
47                            IMO: 0; MMSI: 227205170
48                            IMO: 0; MMSI: 265736720
49   type: Fishing Vessel,  IMO: 9763148; MMSI: 22...
50                            IMO: 0; MMSI: 227847210
51                            IMO: 0; MMSI: 338399517
52                            IMO: 0; MMSI: 257273520
53                            IMO: 0; MMSI: 211505030
54                            IMO: 0; MMSI: 244730710
55                            IMO: 0; MMSI: 236112378
56                            IMO: 0; MMSI: 211632360
57    type: Houseboat,  IMO: 9920629; MMSI: 238698140
58                      IMO: 8889270; MMSI: 273421500
59   type: Crude Oil Tanker,  IMO: 9853400; MMSI: ...
60                            IMO: 0; MMSI: 211528930
61                            IMO: 0; MMSI: 211463540
62                            IMO: 0; MMSI: 211453570
63                            IMO: 0; MMSI: 227484080
64   type: Offshore Supply Ship,  IMO: 9943970; MM...
65                      IMO: 9564358; MMSI: 354598000
66   type: Offshore Supply Ship,  IMO: 9909883; MM...
67   type: Fishing Vessel,  IMO: 8969587; MMSI: 36...
68                            IMO: 0; MMSI: 225991261
69                            IMO: 0; MMSI: 228060910
70   type: Bulk Carrier,  IMO: 9283655; MMSI: 4146...
71   type: Bulk Carrier,  IMO: 9283655; MMSI: 4146...
72   type: Fishing Vessel,  IMO: 8315956; MMSI: 27...
73                            IMO: 0; MMSI: 211117270
74       type: Fishing Vessel,  IMO: 8033168; MMSI: 0
75   type: General Cargo Ship,  IMO: 5031066; MMSI: 0
76       type: Fishing Vessel,  IMO: 7040736; MMSI: 0
77                            IMO: 0; MMSI: 227161030
78                            IMO: 0; MMSI: 247122830
79                            IMO: 0; MMSI: 247190200

In [17]:
#Visualize Ship Names Data Frame with more than 80 Elements (we scraped 2 pages from the website, 40 vessels each, 
#so it cannot match with Ship Details DataFrame
ship_list

                                 Ship Name
0         "AURORA DIAMOND" vessel position
1         "AURORA DIAMOND" vessel position
2           "AURORA DUBAI" vessel position
3        "AURORA ESCAPADE" vessel position
4        "AURORA EXPLORER" vessel position
5        "AURORA EXPLORER" vessel position
6               "AURORA G" vessel position
7          "AURORA GALAXY" vessel position
8         "AURORA HARBOUR" vessel position
9          "AURORA HUNTER" vessel position
10              "AURORA I" vessel position
11              "AURORA I" vessel position
12             "AURORA II" vessel position
13             "AURORA II" vessel position
14            "AURORA III" vessel position
15             "AURORA IV" vessel position
16              "AURORA J" vessel position
17          "AURORA LIGHT" vessel position
18          "AURORA LOPEZ" vessel position
19              "AURORA M" vessel position
20          "AURORA NO. 1" vessel position
21       "AURORA OF ELLOS" vessel position
22      "AURORA OF HAMBLE" vessel position
23          "AURORA PEARL" vessel position
24         "AURORA PETROL" vessel position
25         "AURORA PETROL" vessel position
26        "AURORA POLARIS" vessel position
27        "AURORA POLARIS" vessel position
28        "AURORA POLARIS" vessel position
29      "AURORA PROTECTOR" vessel position
30            "AURORA SAR" vessel position
31         "AURORA SPIRIT" vessel position
32          "AURORA STATT" vessel position
33       "AURORA SURVEYOR" vessel position
34      "AURORA TENDER 10" vessel position
35       "AURORA TENDER 7" vessel position
36              "AURORA V" vessel position
37              "AURORA V" vessel position
38        "AURORA VENTURE" vessel position
39          "AURORA WINDS" vessel position
40
41
42
43
44  "Aurora Af Helsingbor" vessel position
45         "Aurora Bulker" vessel position
46      "Aurora Christine" vessel position
47              "Aurora N" vessel position
48             "Aurora Sb" vessel position
49               "AURORAH" vessel position
50                "AURORE" vessel position
51                "AURORE" vessel position
52                "AURORE" vessel position
53      "AURORE BOREALE 1" vessel position
54            "AURORE III" vessel position
55               "AURORIS" vessel position
56               "AURSOEY" vessel position
57                 "AURUM" vessel position
58                 "AURUM" vessel position
59                 "AURUM" vessel position
60               "AURUM 2" vessel position
61             "AURUM SKY" vessel position
62                 "AURUS" vessel position
63              "AURVIKEN" vessel position
64                 "AURYN" vessel position
65                 "AURYN" vessel position
66                 "AURYN" vessel position
67                "AURYON" vessel position
68           "AUS MAURUGO" vessel position
69           "AUS PIONEER" vessel position
70           "AUS PIONEER" vessel position
71             "AUS WHALE" vessel position
72                "AUSART" vessel position
73                "AUSAYA" vessel position
74               "AUSCA 1" vessel position
75               "AUSCA 1" vessel position
76              "AUSEKLIS" vessel position
77             "AUSGLEICH" vessel position
78                "AUSHRA" vessel position
79          "AUSILIATRICE" vessel position
80                 "AUSMA" vessel position
81                "AUSONE" vessel position
82               "AUSONIA" vessel position
83               "AUSONIA" vessel position
84
85
86
87

In [18]:
# Clean Process for Ship Names Data Frame to match 80 Elements all the time

ship_clean = ship_list.replace('', pd.NA).dropna(axis=0, how='all')
ship_clean.reset_index(drop=True, inplace=True)

ship_clean

                                 Ship Name
0         "AURORA DIAMOND" vessel position
1         "AURORA DIAMOND" vessel position
2           "AURORA DUBAI" vessel position
3        "AURORA ESCAPADE" vessel position
4        "AURORA EXPLORER" vessel position
5        "AURORA EXPLORER" vessel position
6               "AURORA G" vessel position
7          "AURORA GALAXY" vessel position
8         "AURORA HARBOUR" vessel position
9          "AURORA HUNTER" vessel position
10              "AURORA I" vessel position
11              "AURORA I" vessel position
12             "AURORA II" vessel position
13             "AURORA II" vessel position
14            "AURORA III" vessel position
15             "AURORA IV" vessel position
16              "AURORA J" vessel position
17          "AURORA LIGHT" vessel position
18          "AURORA LOPEZ" vessel position
19              "AURORA M" vessel position
20          "AURORA NO. 1" vessel position
21       "AURORA OF ELLOS" vessel position
22      "AURORA OF HAMBLE" vessel position
23          "AURORA PEARL" vessel position
24         "AURORA PETROL" vessel position
25         "AURORA PETROL" vessel position
26        "AURORA POLARIS" vessel position
27        "AURORA POLARIS" vessel position
28        "AURORA POLARIS" vessel position
29      "AURORA PROTECTOR" vessel position
30            "AURORA SAR" vessel position
31         "AURORA SPIRIT" vessel position
32          "AURORA STATT" vessel position
33       "AURORA SURVEYOR" vessel position
34      "AURORA TENDER 10" vessel position
35       "AURORA TENDER 7" vessel position
36              "AURORA V" vessel position
37              "AURORA V" vessel position
38        "AURORA VENTURE" vessel position
39          "AURORA WINDS" vessel position
40  "Aurora Af Helsingbor" vessel position
41         "Aurora Bulker" vessel position
42      "Aurora Christine" vessel position
43              "Aurora N" vessel position
44             "Aurora Sb" vessel position
45               "AURORAH" vessel position
46                "AURORE" vessel position
47                "AURORE" vessel position
48                "AURORE" vessel position
49      "AURORE BOREALE 1" vessel position
50            "AURORE III" vessel position
51               "AURORIS" vessel position
52               "AURSOEY" vessel position
53                 "AURUM" vessel position
54                 "AURUM" vessel position
55                 "AURUM" vessel position
56               "AURUM 2" vessel position
57             "AURUM SKY" vessel position
58                 "AURUS" vessel position
59              "AURVIKEN" vessel position
60                 "AURYN" vessel position
61                 "AURYN" vessel position
62                 "AURYN" vessel position
63                "AURYON" vessel position
64           "AUS MAURUGO" vessel position
65           "AUS PIONEER" vessel position
66           "AUS PIONEER" vessel position
67             "AUS WHALE" vessel position
68                "AUSART" vessel position
69                "AUSAYA" vessel position
70               "AUSCA 1" vessel position
71               "AUSCA 1" vessel position
72              "AUSEKLIS" vessel position
73             "AUSGLEICH" vessel position
74                "AUSHRA" vessel position
75          "AUSILIATRICE" vessel position
76                 "AUSMA" vessel position
77                "AUSONE" vessel position
78               "AUSONIA" vessel position
79               "AUSONIA" vessel position

In [19]:
# Key process to merge both DataFrame and create especific columns for IMO number and MMSI

result = pd.concat([ship_clean['Ship Name'], IMO_list['Ship Details']], axis=1)

result['Ship Name'] = result['Ship Name'].str.replace("'", "").str.replace('"', '').str.replace(" vessel position", "")

result[['IMO', 'MMSI']] = result['Ship Details'].str.split('; MMSI: ', expand=True)


result.drop(columns=['Ship Details'], inplace=True)

result

,Ship Name,IMO,MMSI
0,AURORA DIAMOND,"type: Offshore Supply Ship, IMO: 9648025",636019269
1,AURORA DIAMOND,"type: Offshore Supply Ship, IMO: 9648025",636019269
2,AURORA DUBAI,"type: Research Vessel, IMO: 8717283",210410000
3,AURORA ESCAPADE,IMO: 0,232023677
4,AURORA EXPLORER,"type: Passenger Ship, IMO: 9196723",259560000
5,AURORA EXPLORER,"type: Passenger/Landing Craft, IMO: 7108100",316003415
6,AURORA G,"type: Safety Vessel, IMO: 9604885",372488000
7,AURORA GALAXY,"type: Offshore Supply Ship, IMO: 9748344",258159000
8,AURORA HARBOUR,"type: Tug, IMO: 8794140",525200151
9,AURORA HUNTER,IMO: 0,219026609
10,AURORA I,IMO: 0,258998740
11,AURORA I,IMO: 0,316040487
12,AURORA II,IMO: 0,316040366
13,AURORA II,"type: General Cargo Ship, IMO: 7600706",0
14,AURORA III,IMO: 0,230157390
15,AURORA IV,IMO: 0,235007918
16,AURORA J,IMO: 0,257695600
17,AURORA LIGHT,"type: Wood Chips Carrier, IMO: 9325087",354256000
18,AURORA LOPEZ,IMO: 0,224183630
19,AURORA M,IMO: 0,235074996
20,AURORA NO. 1,"type: Fishing Vessel, IMO: 7804443",0
21,AURORA OF ELLOS,IMO: 0,247034790
22,AURORA OF HAMBLE,IMO: 0,235006731
23,AURORA PEARL,"type: Offshore Supply Ship, IMO: 9638123",636019267
24,AURORA PETROL,"type: Oil Products Tanker, IMO: 9178018",525201572
25,AURORA PETROL,"type: Oil Products Tanker, IMO: 9178018",525201572
26,AURORA POLARIS,IMO: 0,258087150
27,AURORA POLARIS,IMO: 0,258122330
28,AURORA POLARIS,IMO: 0,257945800
29,AURORA PROTECTOR,"type: Offshore Supply Ship, IMO: 9665126",257738000
30,AURORA SAR,"type: Pleasure craft , IMO: 0",211883350
31,AURORA SPIRIT,"type: VL, IMO: 9837169",257086830
32,AURORA STATT,IMO: 0,258268720
33,AURORA SURVEYOR,"type: Research Vessel, IMO: 7108112",0
34,AURORA TENDER 10,IMO: 0,310559020
35,AURORA TENDER 7,IMO: 0,310556030
36,AURORA V,"type: LRS, IMO: 9589774",775992150
37,AURORA V,IMO: 0,257763310
38,AURORA VENTURE,"type: Utility Vessel, IMO: 9653214",235099969
39,AURORA WINDS,IMO: 0,263933990
40,Aurora Af Helsingbor,"type: Passenger Ro Ro Cargo Ship\n, IMO: 900...",265041000
41,Aurora Bulker,"type: Bulk Carrier\n, IMO: 9270919",355489000
42,Aurora Christine,"type: Bulk Carrier\n, IMO: 9214862",525100510
43,Aurora N,"type: Oil Products Tanker\n, IMO: 9346445",373051000
44,Aurora Sb,"type: Bulk Carrier\n, IMO: 9478810",210007000
45,AURORAH,IMO: 0,244025862
46,AURORE,IMO: 0,235075428
47,AURORE,IMO: 0,227205170
48,AURORE,IMO: 0,265736720
49,AURORE BOREALE 1,"type: Fishing Vessel, IMO: 9763148",227989000
50,AURORE III,IMO: 0,227847210
51,AURORIS,IMO: 0,338399517
52,AURSOEY,IMO: 0,257273520
53,AURUM,IMO: 0,211505030
54,AURUM,IMO: 0,244730710
55,AURUM,IMO: 0,236112378
56,AURUM 2,IMO: 0,211632360
57,AURUM SKY,"type: Houseboat, IMO: 9920629",238698140
58,AURUS,IMO: 8889270,273421500
59,AURVIKEN,"type: Crude Oil Tanker, IMO: 9853400",636019492
60,AURYN,IMO: 0,211528930
61,AURYN,IMO: 0,211463540
62,AURYN,IMO: 0,211453570
63,AURYON,IMO: 0,227484080
64,AUS MAURUGO,"type: Offshore Supply Ship, IMO: 9943970",352898724
65,AUS PIONEER,IMO: 9564358,354598000
66,AUS PIONEER,"type: Offshore Supply Ship, IMO: 9909883",0
67,AUS WHALE,"type: Fishing Vessel, IMO: 8969587",367718370
68,AUSART,IMO: 0,225991261
69,AUSAYA,IMO: 0,228060910
70,AUSCA 1,"type: Bulk Carrier, IMO: 9283655",414632000
71,AUSCA 1,"type: Bulk Carrier, IMO: 9283655",414632000
72,AUSEKLIS,"type: Fishing Vessel, IMO: 8315956",275500000
73,AUSGLEICH,IMO: 0,211117270
74,AUSHRA,"type: Fishing Vessel, IMO: 8033168",0
75,AUSILIATRICE,"type: General Cargo Ship, IMO: 5031066",0
76,AUSMA,"type: Fishing Vessel, IMO: 7040736",0
77,AUSONE,IMO: 0,227161030
78,AUSONIA,IMO: 0,247122830
79,AUSONIA,IMO: 0,247190200

In [20]:
# Master Function to extract IMO number and Type from IMO column
def extract_type_and_imonum(imo_str):
    if 'IMO' in imo_str:
        parts = imo_str.split(',')
        imo_number = parts[-1].strip().split(': ')[-1]
        type_ = parts[0].split(': ')[-1].strip()
        return type_, imo_number
    else:
        return '', ''

# Apply the function to extract Type and IMO number
result['Type'], result['IMO number'] = zip(*result['IMO'].apply(extract_type_and_imonum))

# Drop the original 'IMO' column
result.drop(columns=['IMO'], inplace=True)

result

               Ship Name       MMSI                        Type IMO number
0         AURORA DIAMOND  636019269        Offshore Supply Ship    9648025
1         AURORA DIAMOND  636019269        Offshore Supply Ship    9648025
2           AURORA DUBAI  210410000             Research Vessel    8717283
3        AURORA ESCAPADE  232023677                           0          0
4        AURORA EXPLORER  259560000              Passenger Ship    9196723
5        AURORA EXPLORER  316003415     Passenger/Landing Craft    7108100
6               AURORA G  372488000               Safety Vessel    9604885
7          AURORA GALAXY  258159000        Offshore Supply Ship    9748344
8         AURORA HARBOUR  525200151                         Tug    8794140
9          AURORA HUNTER  219026609                           0          0
10              AURORA I  258998740                           0          0
11              AURORA I  316040487                           0          0
12             AURORA II  316040366                           0          0
13             AURORA II          0          General Cargo Ship    7600706
14            AURORA III  230157390                           0          0
15             AURORA IV  235007918                           0          0
16              AURORA J  257695600                           0          0
17          AURORA LIGHT  354256000          Wood Chips Carrier    9325087
18          AURORA LOPEZ  224183630                           0          0
19              AURORA M  235074996                           0          0
20          AURORA NO. 1          0              Fishing Vessel    7804443
21       AURORA OF ELLOS  247034790                           0          0
22      AURORA OF HAMBLE  235006731                           0          0
23          AURORA PEARL  636019267        Offshore Supply Ship    9638123
24         AURORA PETROL  525201572         Oil Products Tanker    9178018
25         AURORA PETROL  525201572         Oil Products Tanker    9178018
26        AURORA POLARIS  258087150                           0          0
27        AURORA POLARIS  258122330                           0          0
28        AURORA POLARIS  257945800                           0          0
29      AURORA PROTECTOR  257738000        Offshore Supply Ship    9665126
30            AURORA SAR  211883350              Pleasure craft          0
31         AURORA SPIRIT  257086830                          VL    9837169
32          AURORA STATT  258268720                           0          0
33       AURORA SURVEYOR          0             Research Vessel    7108112
34      AURORA TENDER 10  310559020                           0          0
35       AURORA TENDER 7  310556030                           0          0
36              AURORA V  775992150                         LRS    9589774
37              AURORA V  257763310                           0          0
38        AURORA VENTURE  235099969              Utility Vessel    9653214
39          AURORA WINDS  263933990                           0          0
40  Aurora Af Helsingbor  265041000  Passenger Ro Ro Cargo Ship    9007128
41         Aurora Bulker  355489000                Bulk Carrier    9270919
42      Aurora Christine  525100510                Bulk Carrier    9214862
43              Aurora N  373051000         Oil Products Tanker    9346445
44             Aurora Sb  210007000                Bulk Carrier    9478810
45               AURORAH  244025862                           0          0
46                AURORE  235075428                           0          0
47                AURORE  227205170                           0          0
48                AURORE  265736720                           0          0
49      AURORE BOREALE 1  227989000              Fishing Vessel    9763148
50            AURORE III  227847210                           0          0
51               AURORIS  338399517                           0          0
52               AURSOEY  257273520                           0          0
53                 AURUM  211505030                           0          0
54                 AURUM  244730710                           0          0
55                 AURUM  236112378                           0          0
56               AURUM 2  211632360                           0          0
57             AURUM SKY  238698140                   Houseboat    9920629
58                 AURUS  273421500                     8889270    8889270
59              AURVIKEN  636019492            Crude Oil Tanker    9853400
60                 AURYN  211528930                           0          0
61                 AURYN  211463540                           0          0
62                 AURYN  211453570                           0          0
63                AURYON  227484080                           0          0
64           AUS MAURUGO  352898724        Offshore Supply Ship    9943970
65           AUS PIONEER  354598000                     9564358    9564358
66           AUS PIONEER          0        Offshore Supply Ship    9909883
67             AUS WHALE  367718370              Fishing Vessel    8969587
68                AUSART  225991261                           0          0
69                AUSAYA  228060910                           0          0
70               AUSCA 1  414632000                Bulk Carrier    9283655
71               AUSCA 1  414632000                Bulk Carrier    9283655
72              AUSEKLIS  275500000              Fishing Vessel    8315956
73             AUSGLEICH  211117270                           0          0
74                AUSHRA          0              Fishing Vessel    8033168
75          AUSILIATRICE          0          General Cargo Ship    5031066
76                 AUSMA          0              Fishing Vessel    7040736
77                AUSONE  227161030                           0          0
78               AUSONIA  247122830                           0          0
79               AUSONIA  247190200                           0          0

In [10]:
# To this point, make another Web Scrapping to Altera to extract in a DataFrame its current fleet
# Send a GET request to the website
url = "https://alterainfra.com/vessels"
response = requests.get(url)

# Parse the HTML content
soup = BeautifulSoup(response.content, 'html.parser')
rows = soup.find_all('tr')


# Initialize lists to store data
vessels = []
types = []
years_built = []

# Extract information from each row
for row in rows:
    data = row.find_all('div', class_='sc-gKsecS lFgBq')
    if len(data) == 4:  # Ensure all required data is present
        vessel = data[0].text.strip()
        vessel_type = data[1].text.strip()
        year_built = data[2].text.strip()
        
        # Append data to lists
        vessels.append(vessel)
        types.append(vessel_type)
        years_built.append(year_built)

# Create DataFrame
Altera = pd.DataFrame({
    'Vessel': vessels,
    'Type': types,
    'Year Built': years_built
})

Altera

,Vessel,Type,Year Built
0,Vessel,Type,Year Built
1,3R-2 Tension Leg Wellhead Platform (TLWP),TLWP,2013
2,3R-3,FPSO,2012
3,Altera Thule,Shuttle Tankers,2022
4,Altera Wave,Shuttle Tankers,2020
5,Altera Wind,Shuttle Tankers,2021
6,Amundsen Spirit,Shuttle Tankers,2010
7,Arendal Spirit,Unit for Maintenance and Safety,2015
8,Aurora Spirit,Shuttle Tankers,2020
9,Beothuk Spirit,Shuttle Tankers,2017
10,Bossa Nova Spirit,Shuttle Tankers,2013
11,Current Spirit,Shuttle Tankers,2020
12,Dorset Spirit,Shuttle Tankers,2018
13,FPSO Cidade de Itajai,FPSO,1995 (Converted to FPSO 2012)
14,FPSO Pioneiro De Libra,FPSO,1995 (Converted to FPSO 2017)
15,Lambada Spirit,Shuttle Tankers,2013
16,Nansen Spirit,Shuttle Tankers,2010
17,Nordic Brasilia,FSO,2004
18,Norse Spirit,Shuttle Tankers,2017
19,Peary Spirit,Shuttle Tankers,2011
20,Petrojarl I,FPSO,1986
21,Petrojarl Knarr,FPSO,2014
22,Piranema Spirit,FPSO,2007
23,Rainbow Spirit,Shuttle Tankers,2020
24,Randgrid,FSO,1995
25,Samba Spirit,Shuttle Tankers,2013
26,Scott Spirit,Shuttle Tankers,2011
27,Sertanejo Spirit,Shuttle Tankers,2013
28,Suksan Salamander,FSO,1993
29,Tide Spirit,Shuttle Tankers,2020
30,Voyageur Spirit,FPSO,2008

In [11]:
#From here, we cross check if in our "result" DataFrame appears in Altera fleet

# Convert ship names to lowercase for case-insensitive comparison
result_ship_names_lower = result['Ship Name'].str.lower().unique()

# Check if ship names exist in Altera DataFrame (case-insensitive)
cross_check = Altera[Altera['Vessel'].str.lower().isin(result_ship_names_lower)]
cross_check

          Vessel             Type Year Built
8  Aurora Spirit  Shuttle Tankers       2020

In [12]:
# Convert ship names to lowercase for case-insensitive comparison
result_ship_names_lowerOP = Altera['Vessel'].str.lower().unique()

# Check if ship names exist in Altera DataFrame (case-insensitive)
cross_check_OP= result[result['Ship Name'].str.lower().isin(result_ship_names_lowerOP)]
cross_check_OP

        Ship Name       MMSI Type IMO number
31  AURORA SPIRIT  257086830   VL    9837169

In [4]:
# #saving the data in excel format
#movie_list.to_excel("Top 1000 IMDb movies.xlsx")

# #If you want to save the data in csv format
#movie_list.to_csv("Top 1000 IMDb movies.csv")

In [22]:
descriptions = soup.find_all('div', class_='description')

for description in descriptions:
    print(description.text.strip())

IMO: 0; MMSI: 200009115
IMO: 0; MMSI: 413841343
IMO: 0; MMSI: 413000049
IMO: 0; MMSI: 413996914
IMO: 0; MMSI: 413816456
IMO: 0; MMSI: 413821785
IMO: 0; MMSI: 413788707
IMO: 0; MMSI: 413932414
IMO: 0; MMSI: 413930365
IMO: 0; MMSI: 710004393
IMO: 0; MMSI: 413795004
IMO: 0; MMSI: 413825716
IMO: 0; MMSI: 413767637
IMO: 0; MMSI: 800014213
IMO: 0; MMSI: 413826231
IMO: 0; MMSI: 413821758
IMO: 0; MMSI: 413794914
IMO: 0; MMSI: 413826222
IMO: 0; MMSI: 413804691
IMO: 0; MMSI: 413804697
IMO: 0; MMSI: 413834076
IMO: 0; MMSI: 413782943
IMO: 0; MMSI: 413769131
IMO: 0; MMSI: 413962255
IMO: 0; MMSI: 413825447
IMO: 0; MMSI: 119072605
IMO: 0; MMSI: 119072606
IMO: 0; MMSI: 131103013
IMO: 9707912; MMSI: 533130421
IMO: 0; MMSI: 375544000
IMO: 0; MMSI: 367710250
IMO: 0; MMSI: 316030839
IMO: 0; MMSI: 100121010
IMO: 9795103; MMSI: 228091700
IMO: 9858577; MMSI: 563110700
IMO: 9858565; MMSI: 563109500
IMO: 9858553; MMSI: 563104300
IMO: 0; MMSI: 735059489
IMO: 9739513; MMSI: 563032500
IMO: 0; MMSI: 671056100